-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 17:18:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_campo_pozos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_campo_pozos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_campo_pozos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_campo_pozos` ;

-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `Identificacion` INT NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Identificacion_UNIQUE` (`Identificacion` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`registropozos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`registropozos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cluster` VARCHAR(45) NOT NULL,
  `Campo` VARCHAR(45) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL DEFAULT 'activo',
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_campo_pozos`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`constantespozo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`constantespozo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `API` FLOAT NOT NULL,
  `GOR` FLOAT NOT NULL,
  `API_N` FLOAT NOT NULL,
  `CW` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `pozo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pozo_id_idx` (`pozo_id` ASC) VISIBLE,
  CONSTRAINT `pozo_id`
    FOREIGN KEY (`pozo_id`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`ipplcn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`ipplcn` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IP` VARCHAR(45) NOT NULL,
  `slave` VARCHAR(45) NOT NULL,
  `dirreg` VARCHAR(45) NOT NULL,
  `tiporeg` VARCHAR(45) NOT NULL,
  `tiporeghi` VARCHAR(45) NOT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_1_idx` (`id_pozo` ASC) VISIBLE,
  CONSTRAINT `id_pozo_1`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`ipsf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`ipsf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IP` VARCHAR(45) NOT NULL,
  `slave` VARCHAR(45) NOT NULL,
  `dirreg` VARCHAR(45) NOT NULL,
  `tiporeg` VARCHAR(45) NOT NULL,
  `tiporeghi` VARCHAR(45) NOT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_2_idx` (`id_pozo` ASC) VISIBLE,
  CONSTRAINT `id_pozo_2`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`ipss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`ipss` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IP` VARCHAR(45) NOT NULL,
  `slave` VARCHAR(45) NOT NULL,
  `dirreg` VARCHAR(45) NOT NULL,
  `tiporeg` VARCHAR(45) NOT NULL,
  `tiporeghi` VARCHAR(45) NOT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_3_idx` (`id_pozo` ASC) INVISIBLE,
  CONSTRAINT `id_pozo_3`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`ipvsd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`ipvsd` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IP` VARCHAR(45) NOT NULL,
  `slave` VARCHAR(45) NOT NULL,
  `dirreg` VARCHAR(45) NOT NULL,
  `tiporeg` VARCHAR(45) NOT NULL,
  `tiporeghi` VARCHAR(45) NOT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_4_idx` (`id_pozo` ASC) VISIBLE,
  CONSTRAINT `id_pozo_4`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`sensorfondo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`sensorfondo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `p_intake` FLOAT NULL DEFAULT NULL,
  `p_descarga` FLOAT NULL DEFAULT NULL,
  `t_intake` FLOAT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_sf_idx` (`id_pozo` ASC) VISIBLE,
  CONSTRAINT `id_pozo_sf`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`sensorplcn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`sensorplcn` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flujo` FLOAT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_plcn_idx` (`id_pozo` ASC) VISIBLE,
  CONSTRAINT `id_pozo_plcn`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`sensorsuperf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`sensorsuperf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `p_cabeza` FLOAT NULL DEFAULT NULL,
  `t_cabeza` FLOAT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_superf_idx` (`id_pozo` ASC) VISIBLE,
  CONSTRAINT `id_pozo_superf`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`sensorvsd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`sensorvsd` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `frecuencia` FLOAT NULL DEFAULT NULL,
  `corriente` FLOAT NULL DEFAULT NULL,
  `voltaje` FLOAT NULL DEFAULT NULL,
  `fp` FLOAT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `id_pozo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pozo_vsd_idx` (`id_pozo` ASC) VISIBLE,
  CONSTRAINT `id_pozo_vsd`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `bd_campo_pozos`.`registropozos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_campo_pozos`.`tablaue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campo_pozos`.`tablaue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unidad` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
